### ISSUE TITLE
Question: time-based daemon

### ISSUE THREAD

**Issue by howeyc** [d4l3k/go-sct#5]
What are your thoughts on making the sct daemon adjust temperature based on time (perhaps setting the temperature every 15 min)?

ie.

--sunrise-time "06:00" --sunrise-temp 4500 \
--brightest-time "14:00" --brightest-temp 8600 \
--sunset-time "21:00" --sunset-temp 3000 \
--adjust-duration-secs "900"

This way you could have an afternoon "jolt" of blue light (if you set it that way). Also, this would work for people that have a schedule that is consistent regardless of the what sun is doing (most people's office hours are consistent throughout the year).

**Comment by d4l3k** [comment]
I can definitely see that as a use case. I personally am fine with the color based on time since I mostly use this to fix my sleep schedule.

Feel free to add it. If you do, try and make it do a smooth transition (delta = 100?) during the time period. I'm thinking about adding finer time temperature increments. Also, could be interesting to try and implement benzine curves to hide any hard transitions as well as provide really fine control to users.

**Comment by d4l3k** [comment]
Since this got merged in a while back, I guess this issue is resolved.
